# Generated by Django 3.1.4 on 2021-01-10 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(default='N/A', max_length=50)),
                ('Author_title', models.CharField(default='N/A', max_length=50)),
                ('Summary', models.CharField(default='N/A', max_length=500)),
                ('Date_published', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=50)),
                ('DateCreated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTitle', models.CharField(default='N/A', max_length=30)),
                ('genre', models.CharField(choices=[('Ac', 'Action'), ('R', 'rpg'), ('HR', 'horror'), ('JR', 'jrpg'), ('ND', 'narative driven')], max_length=2)),
                ('Producers', models.CharField(default='Anonymous', max_length=50)),
                ('Summary', models.TextField(default='N/A', max_length=500)),
                ('platform', models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='myWeb.platform')),
            ],
        ),
    ]
