# Generated by Django 3.1.4 on 2021-01-10 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0002_remove_game_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myWeb.platform'),
        ),
    ]
